export const htmlContent = [
	'<style>',
	'\th1 {',
	'\t\tcolor: red;',
	'\t}',
	'</style>',
	'',
	'<h1 onclick="onClick()">Welcome</h1>', 
	'<p>Hello World</p>',
	'',
	'<script>',
	'\tfunction onClick() {',
	'\t\talert("Hello World");',
	'\t}',
	'</script>',
];